
package clients.numberConversion;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * The Number Conversion Web Service, implemented with Visual DataFlex, provides functions that convert numbers into words or dollar amounts.
 * 
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "NumberConversion", targetNamespace = "http://www.dataaccess.com/webservicesserver/", wsdlLocation = "https://www.dataaccess.com/webservicesserver/NumberConversion.wso?wsdl")
public class NumberConversion
    extends Service
{

    private static final URL NUMBERCONVERSION_WSDL_LOCATION;
    private static final WebServiceException NUMBERCONVERSION_EXCEPTION;
    private static final QName NUMBERCONVERSION_QNAME = new QName("http://www.dataaccess.com/webservicesserver/", "NumberConversion");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://www.dataaccess.com/webservicesserver/NumberConversion.wso?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NUMBERCONVERSION_WSDL_LOCATION = url;
        NUMBERCONVERSION_EXCEPTION = e;
    }

    public NumberConversion() {
        super(__getWsdlLocation(), NUMBERCONVERSION_QNAME);
    }

    public NumberConversion(WebServiceFeature... features) {
        super(__getWsdlLocation(), NUMBERCONVERSION_QNAME, features);
    }

    public NumberConversion(URL wsdlLocation) {
        super(wsdlLocation, NUMBERCONVERSION_QNAME);
    }

    public NumberConversion(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NUMBERCONVERSION_QNAME, features);
    }

    public NumberConversion(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NumberConversion(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NumberConversionSoapType
     */
    @WebEndpoint(name = "NumberConversionSoap")
    public NumberConversionSoapType getNumberConversionSoap() {
        return super.getPort(new QName("http://www.dataaccess.com/webservicesserver/", "NumberConversionSoap"), NumberConversionSoapType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NumberConversionSoapType
     */
    @WebEndpoint(name = "NumberConversionSoap")
    public NumberConversionSoapType getNumberConversionSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.dataaccess.com/webservicesserver/", "NumberConversionSoap"), NumberConversionSoapType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NUMBERCONVERSION_EXCEPTION!= null) {
            throw NUMBERCONVERSION_EXCEPTION;
        }
        return NUMBERCONVERSION_WSDL_LOCATION;
    }

}
